# Change these first
owner: kemp # Your GitHub organization or username, where this repository lives
repo: healthcheck # The name of this repository

sites:
  - name: CamFlip API
    url: https://camflip.net/api/v1/activations/$CF_ACTIVATION
  - name: CamFlip Home
    url: https://camflip.net
  - name: CamFlip License
    url: https://camflip.net/licenses/$CF_LICENSE
  - name: CamFlip Purchase Page
    url: https://camflip.net/purchase
  - name: GlobalOffset.com
    url: https://globaloffset.com/
  - name: Kemp.app
    url: https://kemp.app
  - name: Kitboga.com
    url: https://kitboga.com
  - name: Bingo.Kitboga.com
    url: https://bingo.kitboga.com
  - name: Kitboga.com/out
    url: https://kitboga.com/out?url=https%3A%2F%2Fyoutube.com%2Fc%2FKitbogaShow&signature=774be8c8438adb1bdafa7e6a7c2e3285759dcc77367c68a02f5d5021fbb8f9bb
  - name: Videomirror.app
    url: https://videomirror.app
  - name: Videomirror.app/donate
    url: https://videomirror.app/donate

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /healthcheck
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Healthcheck
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

assignees:
  - kemp

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
